### ISSUE TITLE
Input Github URLs

### ISSUE THREAD

**Issue by jbenet** [noffle/github-dependency-crawl#12]
As a user of this module, it would be really nice to be able to input direct github URLs, like:

```js
// repo
crawl("https://github.com/noffle/github-dependency-crawl", cb)

// single issue
crawl("https://github.com/noffle/github-dependency-crawl/issues/3", cb)

// whole user/org (expensive!)
crawl("https://gitehub.com/noffle", cb)
```

You can use this regexp to grab out the relevant details, [i tested it some](https://gist.github.com/jbenet/fe154f426b03b431d35ee9acc6d7a85b):

```js
var re = /^(https?:)?(\/\/)?github\.com\/([^/]+)(\/([^/]+)(\/(issues|pulls?)(\/([0-9]+))?)?)?\/?$/

var getParts = function(s) {
  var g = re.exec(s)
  var obj = {}

  if (g) {
    if (g[3]) obj.user = g[3]
    if (g[5]) obj.repo = g[5]
    if (g[9]) obj.issue = g[9]
  }
  return obj
}
```

**Comment by noffle** [comment]
Hey @jbenet, could you say more about your use case? What makes `https://github.com/noffle/talks` more desirable than the much shorter `noffle/talks`?

**Comment by noffle** [comment]
I thought about this and it seems reasonable. Added in https://github.com/noffle/github-dependency-crawl/commit/8f1f5cca0fbd62c7b38a305085fea32f95be4694.

**Comment by jbenet** [comment]
My desires were for being able to quickly copy and paste from an existing
URL instead of typing. (And conceivably fetching from other entities, like
gitlab in the future. Making the URL the identifier makes it decentralized.
If not this one, clients of his module may want to do that.)

**Comment by noffle** [comment]
Ah, I see your intent now. You were thinking of the URL as a signal to the crawler to decide what backend to use as its datasource.

My plan was the reverse relationship: a user of this module would provide a backend module that implements the "issue fetch" api, so that just the canonical `:org/:repo` would be sufficient.
