### ISSUE TITLE
Dependency metadata

### ISSUE THREAD

**Issue by noffle** [noffle/github-dependency-crawl#9]
Eventually it will be nice to let the pluggable functions associate metadata with dependencies, which will require more structured data. E.g.

```js
{
  'noffle/github-dependency-crawl/12': {
    state: 'closed',
    dependencies: [ ... ]
  }
}
```

This may also mean more pluggable functions to e.g. decide whether to recursive more deeply (if, say, the issue is resolved).

**Comment by hackergrrl** [comment]
This'll come for free once we're storing the raw issue data in the dep graph: https://github.com/noffle/github-dependency-crawl/issues/14
